name: Azd Automation
on:
  workflow_dispatch:

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install azd
        uses: Azure/setup-azd@0b7e3a35ab00f2eee7080c845eb39c3f0ebfa553 # v2.4.0

      - name: Install Az extensions
        run: |
          azd config set alpha.aks.helm on

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login \
            --client-id ${{env.AZURE_CLIENT_ID}} \
            --federated-credential-provider "github" \
            --tenant-id ${{env.AZURE_TENANT_ID}}

      - name: Azure login
        uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{env.AZURE_CLIENT_ID}}
          tenant-id: ${{env.AZURE_TENANT_ID}}
          subscription-id: ${{env.AZURE_SUBSCRIPTION_ID}}

      - name: Set environment name with timestamp
        id: set_env_name
        run: |
          current_time=$(date +%m%d%H%M)
          azure_env_name="${{ env.AZURE_ENV_NAME }}-$current_time"
          echo "AZURE_ENV_NAME=$azure_env_name" >> $GITHUB_ENV
          echo "azure_env_name is $azure_env_name"
        shell: bash
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}

      - name: AZD UP
        run: |
          azd up --no-prompt

      - name: AZD Down
        run: |
          azd down

      - name: Show azd environments
        run: |
          azd env list
          azd env get-values